display_name: Linx Music
icon: android/app/src/main/res/playstore-icon.png
generic_name: Music Player

keywords:
  - Music
  - Audio
  - Player

categories:
  - AudioVideo
  - Audio
  - Player

startup_notify: true
metainfo: linux/packaging/linx_music.appdata.xml

include: []
